# Name and metadata of your task
task_name: "NYTimes Scraper v0.0.2"
author: "Soma"
description: "This task scrapes the NYTimes website and stores the data in a file. Select a locale to scrape, it will fetch the list on homepage, for each it will fetch the title, author, date, and content. The content gonna upload to IPFS and save as cid. It will then store the list of data in a file and upload it to IPFS. Your submission will contain the cid of the article list and the cid of the article list. "
repositoryUrl: "https://github.com/somali0128/nytimes-crawler"
imageUrl: "imageUrl"

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: "IPFS"

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: "dist/main.js"

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 2000

audit_window: 500
submission_window: 500

# Amounts in KOII

minimum_stake_amount: 2

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 100

bounty_amount_per_round: 1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: TASK_VARIABLE
    value: "LOCALE"
    description: 'By default, the task will fetch data from the US. If you wish to specify a different locale, select the one from which you'd like to scrape data. Options include "US" for the United States, "CN" for China, and "ES" for Spain. If you leave this field empty, the system will default to the US.'
  - type: TASK_VARIABLE
    value: "SECRET_WEB3_STORAGE_KEY"
    description: 'To upload the executable to IPFS, you will need a web3 storage key. You can obtain one for yourself by following the tutorial at https://blog.koii.network/Introduce-web3-storage/. This tutorial will guide you on how to get the required web3 storage key for IPFS uploading.'
  - type: TASK_VARIABLE
    value: "DEBUG_MODE"
    description: 'The debug mode is optional and by default set to 'false'. If you wish to activate debug mode, select 'true' from the options. Leaving this field blank will keep the default setting, i.e., debug mode off. Be aware that activating debug mode might cause the task to be interrupted. When activated, the Chromium window will appear during task execution.'
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "5 GB"

# OPTIONAL variables below 

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: "5JvBKywe7JLA99QT6jawbNwWUoi8cXnueXbGK8vVbB6N"

# OPTIONAL only Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: "main"